version: '3.1'

services:
  joomla:
    image: joomla:latest
    restart: always
    links:
      - joomladb:mariadb
    ports:
      - 80:80
    environment:
      JOOMLA_DB_HOST: joomladb:3306
      JOOMLA_DB_USER: joomla
      JOOMLA_DB_PASSWORD: joomla123

  joomladb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: joomla123
      MYSQL_USER: joomla
      MYSQL_PASSWORD: joomla123
      MYSQL_DATABASE: joomla

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1